# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.17.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.17.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ronald/Desktop/DBSE---Project/CODD-pro-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ronald/Desktop/DBSE---Project/CODD-pro-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.17.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.17.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ronald/Desktop/DBSE---Project/CODD-pro-master/CMakeFiles /Users/ronald/Desktop/DBSE---Project/CODD-pro-master/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ronald/Desktop/DBSE---Project/CODD-pro-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Hero

# Build rule for target.
Hero: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Hero
.PHONY : Hero

# fast build rule for target.
Hero/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/build
.PHONY : Hero/fast

TPCH/common/algebra/Operators.o: TPCH/common/algebra/Operators.cpp.o

.PHONY : TPCH/common/algebra/Operators.o

# target to build an object file
TPCH/common/algebra/Operators.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/algebra/Operators.cpp.o
.PHONY : TPCH/common/algebra/Operators.cpp.o

TPCH/common/algebra/Operators.i: TPCH/common/algebra/Operators.cpp.i

.PHONY : TPCH/common/algebra/Operators.i

# target to preprocess a source file
TPCH/common/algebra/Operators.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/algebra/Operators.cpp.i
.PHONY : TPCH/common/algebra/Operators.cpp.i

TPCH/common/algebra/Operators.s: TPCH/common/algebra/Operators.cpp.s

.PHONY : TPCH/common/algebra/Operators.s

# target to generate assembly for a file
TPCH/common/algebra/Operators.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/algebra/Operators.cpp.s
.PHONY : TPCH/common/algebra/Operators.cpp.s

TPCH/common/algebra/Pipeline.o: TPCH/common/algebra/Pipeline.cpp.o

.PHONY : TPCH/common/algebra/Pipeline.o

# target to build an object file
TPCH/common/algebra/Pipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/algebra/Pipeline.cpp.o
.PHONY : TPCH/common/algebra/Pipeline.cpp.o

TPCH/common/algebra/Pipeline.i: TPCH/common/algebra/Pipeline.cpp.i

.PHONY : TPCH/common/algebra/Pipeline.i

# target to preprocess a source file
TPCH/common/algebra/Pipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/algebra/Pipeline.cpp.i
.PHONY : TPCH/common/algebra/Pipeline.cpp.i

TPCH/common/algebra/Pipeline.s: TPCH/common/algebra/Pipeline.cpp.s

.PHONY : TPCH/common/algebra/Pipeline.s

# target to generate assembly for a file
TPCH/common/algebra/Pipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/algebra/Pipeline.cpp.s
.PHONY : TPCH/common/algebra/Pipeline.cpp.s

TPCH/common/algebra/Types.o: TPCH/common/algebra/Types.cpp.o

.PHONY : TPCH/common/algebra/Types.o

# target to build an object file
TPCH/common/algebra/Types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/algebra/Types.cpp.o
.PHONY : TPCH/common/algebra/Types.cpp.o

TPCH/common/algebra/Types.i: TPCH/common/algebra/Types.cpp.i

.PHONY : TPCH/common/algebra/Types.i

# target to preprocess a source file
TPCH/common/algebra/Types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/algebra/Types.cpp.i
.PHONY : TPCH/common/algebra/Types.cpp.i

TPCH/common/algebra/Types.s: TPCH/common/algebra/Types.cpp.s

.PHONY : TPCH/common/algebra/Types.s

# target to generate assembly for a file
TPCH/common/algebra/Types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/algebra/Types.cpp.s
.PHONY : TPCH/common/algebra/Types.cpp.s

TPCH/common/runtime/Concurrency.o: TPCH/common/runtime/Concurrency.cpp.o

.PHONY : TPCH/common/runtime/Concurrency.o

# target to build an object file
TPCH/common/runtime/Concurrency.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/Concurrency.cpp.o
.PHONY : TPCH/common/runtime/Concurrency.cpp.o

TPCH/common/runtime/Concurrency.i: TPCH/common/runtime/Concurrency.cpp.i

.PHONY : TPCH/common/runtime/Concurrency.i

# target to preprocess a source file
TPCH/common/runtime/Concurrency.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/Concurrency.cpp.i
.PHONY : TPCH/common/runtime/Concurrency.cpp.i

TPCH/common/runtime/Concurrency.s: TPCH/common/runtime/Concurrency.cpp.s

.PHONY : TPCH/common/runtime/Concurrency.s

# target to generate assembly for a file
TPCH/common/runtime/Concurrency.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/Concurrency.cpp.s
.PHONY : TPCH/common/runtime/Concurrency.cpp.s

TPCH/common/runtime/Database.o: TPCH/common/runtime/Database.cpp.o

.PHONY : TPCH/common/runtime/Database.o

# target to build an object file
TPCH/common/runtime/Database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/Database.cpp.o
.PHONY : TPCH/common/runtime/Database.cpp.o

TPCH/common/runtime/Database.i: TPCH/common/runtime/Database.cpp.i

.PHONY : TPCH/common/runtime/Database.i

# target to preprocess a source file
TPCH/common/runtime/Database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/Database.cpp.i
.PHONY : TPCH/common/runtime/Database.cpp.i

TPCH/common/runtime/Database.s: TPCH/common/runtime/Database.cpp.s

.PHONY : TPCH/common/runtime/Database.s

# target to generate assembly for a file
TPCH/common/runtime/Database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/Database.cpp.s
.PHONY : TPCH/common/runtime/Database.cpp.s

TPCH/common/runtime/Hashmap.o: TPCH/common/runtime/Hashmap.cpp.o

.PHONY : TPCH/common/runtime/Hashmap.o

# target to build an object file
TPCH/common/runtime/Hashmap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/Hashmap.cpp.o
.PHONY : TPCH/common/runtime/Hashmap.cpp.o

TPCH/common/runtime/Hashmap.i: TPCH/common/runtime/Hashmap.cpp.i

.PHONY : TPCH/common/runtime/Hashmap.i

# target to preprocess a source file
TPCH/common/runtime/Hashmap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/Hashmap.cpp.i
.PHONY : TPCH/common/runtime/Hashmap.cpp.i

TPCH/common/runtime/Hashmap.s: TPCH/common/runtime/Hashmap.cpp.s

.PHONY : TPCH/common/runtime/Hashmap.s

# target to generate assembly for a file
TPCH/common/runtime/Hashmap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/Hashmap.cpp.s
.PHONY : TPCH/common/runtime/Hashmap.cpp.s

TPCH/common/runtime/Import.o: TPCH/common/runtime/Import.cpp.o

.PHONY : TPCH/common/runtime/Import.o

# target to build an object file
TPCH/common/runtime/Import.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/Import.cpp.o
.PHONY : TPCH/common/runtime/Import.cpp.o

TPCH/common/runtime/Import.i: TPCH/common/runtime/Import.cpp.i

.PHONY : TPCH/common/runtime/Import.i

# target to preprocess a source file
TPCH/common/runtime/Import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/Import.cpp.i
.PHONY : TPCH/common/runtime/Import.cpp.i

TPCH/common/runtime/Import.s: TPCH/common/runtime/Import.cpp.s

.PHONY : TPCH/common/runtime/Import.s

# target to generate assembly for a file
TPCH/common/runtime/Import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/Import.cpp.s
.PHONY : TPCH/common/runtime/Import.cpp.s

TPCH/common/runtime/MemoryPool.o: TPCH/common/runtime/MemoryPool.cpp.o

.PHONY : TPCH/common/runtime/MemoryPool.o

# target to build an object file
TPCH/common/runtime/MemoryPool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/MemoryPool.cpp.o
.PHONY : TPCH/common/runtime/MemoryPool.cpp.o

TPCH/common/runtime/MemoryPool.i: TPCH/common/runtime/MemoryPool.cpp.i

.PHONY : TPCH/common/runtime/MemoryPool.i

# target to preprocess a source file
TPCH/common/runtime/MemoryPool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/MemoryPool.cpp.i
.PHONY : TPCH/common/runtime/MemoryPool.cpp.i

TPCH/common/runtime/MemoryPool.s: TPCH/common/runtime/MemoryPool.cpp.s

.PHONY : TPCH/common/runtime/MemoryPool.s

# target to generate assembly for a file
TPCH/common/runtime/MemoryPool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/MemoryPool.cpp.s
.PHONY : TPCH/common/runtime/MemoryPool.cpp.s

TPCH/common/runtime/Profile.o: TPCH/common/runtime/Profile.cpp.o

.PHONY : TPCH/common/runtime/Profile.o

# target to build an object file
TPCH/common/runtime/Profile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/Profile.cpp.o
.PHONY : TPCH/common/runtime/Profile.cpp.o

TPCH/common/runtime/Profile.i: TPCH/common/runtime/Profile.cpp.i

.PHONY : TPCH/common/runtime/Profile.i

# target to preprocess a source file
TPCH/common/runtime/Profile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/Profile.cpp.i
.PHONY : TPCH/common/runtime/Profile.cpp.i

TPCH/common/runtime/Profile.s: TPCH/common/runtime/Profile.cpp.s

.PHONY : TPCH/common/runtime/Profile.s

# target to generate assembly for a file
TPCH/common/runtime/Profile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/Profile.cpp.s
.PHONY : TPCH/common/runtime/Profile.cpp.s

TPCH/common/runtime/String.o: TPCH/common/runtime/String.cpp.o

.PHONY : TPCH/common/runtime/String.o

# target to build an object file
TPCH/common/runtime/String.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/String.cpp.o
.PHONY : TPCH/common/runtime/String.cpp.o

TPCH/common/runtime/String.i: TPCH/common/runtime/String.cpp.i

.PHONY : TPCH/common/runtime/String.i

# target to preprocess a source file
TPCH/common/runtime/String.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/String.cpp.i
.PHONY : TPCH/common/runtime/String.cpp.i

TPCH/common/runtime/String.s: TPCH/common/runtime/String.cpp.s

.PHONY : TPCH/common/runtime/String.s

# target to generate assembly for a file
TPCH/common/runtime/String.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/String.cpp.s
.PHONY : TPCH/common/runtime/String.cpp.s

TPCH/common/runtime/Types.o: TPCH/common/runtime/Types.cpp.o

.PHONY : TPCH/common/runtime/Types.o

# target to build an object file
TPCH/common/runtime/Types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/Types.cpp.o
.PHONY : TPCH/common/runtime/Types.cpp.o

TPCH/common/runtime/Types.i: TPCH/common/runtime/Types.cpp.i

.PHONY : TPCH/common/runtime/Types.i

# target to preprocess a source file
TPCH/common/runtime/Types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/Types.cpp.i
.PHONY : TPCH/common/runtime/Types.cpp.i

TPCH/common/runtime/Types.s: TPCH/common/runtime/Types.cpp.s

.PHONY : TPCH/common/runtime/Types.s

# target to generate assembly for a file
TPCH/common/runtime/Types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/common/runtime/Types.cpp.s
.PHONY : TPCH/common/runtime/Types.cpp.s

TPCH/tpch_globals.o: TPCH/tpch_globals.cpp.o

.PHONY : TPCH/tpch_globals.o

# target to build an object file
TPCH/tpch_globals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/tpch_globals.cpp.o
.PHONY : TPCH/tpch_globals.cpp.o

TPCH/tpch_globals.i: TPCH/tpch_globals.cpp.i

.PHONY : TPCH/tpch_globals.i

# target to preprocess a source file
TPCH/tpch_globals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/tpch_globals.cpp.i
.PHONY : TPCH/tpch_globals.cpp.i

TPCH/tpch_globals.s: TPCH/tpch_globals.cpp.s

.PHONY : TPCH/tpch_globals.s

# target to generate assembly for a file
TPCH/tpch_globals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/TPCH/tpch_globals.cpp.s
.PHONY : TPCH/tpch_globals.cpp.s

cpp_layer/cpp_globals.o: cpp_layer/cpp_globals.cpp.o

.PHONY : cpp_layer/cpp_globals.o

# target to build an object file
cpp_layer/cpp_globals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/cpp_layer/cpp_globals.cpp.o
.PHONY : cpp_layer/cpp_globals.cpp.o

cpp_layer/cpp_globals.i: cpp_layer/cpp_globals.cpp.i

.PHONY : cpp_layer/cpp_globals.i

# target to preprocess a source file
cpp_layer/cpp_globals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/cpp_layer/cpp_globals.cpp.i
.PHONY : cpp_layer/cpp_globals.cpp.i

cpp_layer/cpp_globals.s: cpp_layer/cpp_globals.cpp.s

.PHONY : cpp_layer/cpp_globals.s

# target to generate assembly for a file
cpp_layer/cpp_globals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/cpp_layer/cpp_globals.cpp.s
.PHONY : cpp_layer/cpp_globals.cpp.s

cpp_layer/operations/primitives.o: cpp_layer/operations/primitives.cpp.o

.PHONY : cpp_layer/operations/primitives.o

# target to build an object file
cpp_layer/operations/primitives.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/cpp_layer/operations/primitives.cpp.o
.PHONY : cpp_layer/operations/primitives.cpp.o

cpp_layer/operations/primitives.i: cpp_layer/operations/primitives.cpp.i

.PHONY : cpp_layer/operations/primitives.i

# target to preprocess a source file
cpp_layer/operations/primitives.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/cpp_layer/operations/primitives.cpp.i
.PHONY : cpp_layer/operations/primitives.cpp.i

cpp_layer/operations/primitives.s: cpp_layer/operations/primitives.cpp.s

.PHONY : cpp_layer/operations/primitives.s

# target to generate assembly for a file
cpp_layer/operations/primitives.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/cpp_layer/operations/primitives.cpp.s
.PHONY : cpp_layer/operations/primitives.cpp.s

cpp_layer/tests/test_cpp_execution.o: cpp_layer/tests/test_cpp_execution.cpp.o

.PHONY : cpp_layer/tests/test_cpp_execution.o

# target to build an object file
cpp_layer/tests/test_cpp_execution.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/cpp_layer/tests/test_cpp_execution.cpp.o
.PHONY : cpp_layer/tests/test_cpp_execution.cpp.o

cpp_layer/tests/test_cpp_execution.i: cpp_layer/tests/test_cpp_execution.cpp.i

.PHONY : cpp_layer/tests/test_cpp_execution.i

# target to preprocess a source file
cpp_layer/tests/test_cpp_execution.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/cpp_layer/tests/test_cpp_execution.cpp.i
.PHONY : cpp_layer/tests/test_cpp_execution.cpp.i

cpp_layer/tests/test_cpp_execution.s: cpp_layer/tests/test_cpp_execution.cpp.s

.PHONY : cpp_layer/tests/test_cpp_execution.s

# target to generate assembly for a file
cpp_layer/tests/test_cpp_execution.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/cpp_layer/tests/test_cpp_execution.cpp.s
.PHONY : cpp_layer/tests/test_cpp_execution.cpp.s

globals.o: globals.cpp.o

.PHONY : globals.o

# target to build an object file
globals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/globals.cpp.o
.PHONY : globals.cpp.o

globals.i: globals.cpp.i

.PHONY : globals.i

# target to preprocess a source file
globals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/globals.cpp.i
.PHONY : globals.cpp.i

globals.s: globals.cpp.s

.PHONY : globals.s

# target to generate assembly for a file
globals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/globals.cpp.s
.PHONY : globals.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/main.cpp.s
.PHONY : main.cpp.s

opencl_layer/classes/devices.o: opencl_layer/classes/devices.cpp.o

.PHONY : opencl_layer/classes/devices.o

# target to build an object file
opencl_layer/classes/devices.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/opencl_layer/classes/devices.cpp.o
.PHONY : opencl_layer/classes/devices.cpp.o

opencl_layer/classes/devices.i: opencl_layer/classes/devices.cpp.i

.PHONY : opencl_layer/classes/devices.i

# target to preprocess a source file
opencl_layer/classes/devices.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/opencl_layer/classes/devices.cpp.i
.PHONY : opencl_layer/classes/devices.cpp.i

opencl_layer/classes/devices.s: opencl_layer/classes/devices.cpp.s

.PHONY : opencl_layer/classes/devices.s

# target to generate assembly for a file
opencl_layer/classes/devices.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/opencl_layer/classes/devices.cpp.s
.PHONY : opencl_layer/classes/devices.cpp.s

opencl_layer/classes/platforms.o: opencl_layer/classes/platforms.cpp.o

.PHONY : opencl_layer/classes/platforms.o

# target to build an object file
opencl_layer/classes/platforms.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/opencl_layer/classes/platforms.cpp.o
.PHONY : opencl_layer/classes/platforms.cpp.o

opencl_layer/classes/platforms.i: opencl_layer/classes/platforms.cpp.i

.PHONY : opencl_layer/classes/platforms.i

# target to preprocess a source file
opencl_layer/classes/platforms.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/opencl_layer/classes/platforms.cpp.i
.PHONY : opencl_layer/classes/platforms.cpp.i

opencl_layer/classes/platforms.s: opencl_layer/classes/platforms.cpp.s

.PHONY : opencl_layer/classes/platforms.s

# target to generate assembly for a file
opencl_layer/classes/platforms.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/opencl_layer/classes/platforms.cpp.s
.PHONY : opencl_layer/classes/platforms.cpp.s

opencl_layer/openCL_globals.o: opencl_layer/openCL_globals.cpp.o

.PHONY : opencl_layer/openCL_globals.o

# target to build an object file
opencl_layer/openCL_globals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/opencl_layer/openCL_globals.cpp.o
.PHONY : opencl_layer/openCL_globals.cpp.o

opencl_layer/openCL_globals.i: opencl_layer/openCL_globals.cpp.i

.PHONY : opencl_layer/openCL_globals.i

# target to preprocess a source file
opencl_layer/openCL_globals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/opencl_layer/openCL_globals.cpp.i
.PHONY : opencl_layer/openCL_globals.cpp.i

opencl_layer/openCL_globals.s: opencl_layer/openCL_globals.cpp.s

.PHONY : opencl_layer/openCL_globals.s

# target to generate assembly for a file
opencl_layer/openCL_globals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/opencl_layer/openCL_globals.cpp.s
.PHONY : opencl_layer/openCL_globals.cpp.s

opencl_layer/tests/test_openCL_execution.o: opencl_layer/tests/test_openCL_execution.cpp.o

.PHONY : opencl_layer/tests/test_openCL_execution.o

# target to build an object file
opencl_layer/tests/test_openCL_execution.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/opencl_layer/tests/test_openCL_execution.cpp.o
.PHONY : opencl_layer/tests/test_openCL_execution.cpp.o

opencl_layer/tests/test_openCL_execution.i: opencl_layer/tests/test_openCL_execution.cpp.i

.PHONY : opencl_layer/tests/test_openCL_execution.i

# target to preprocess a source file
opencl_layer/tests/test_openCL_execution.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/opencl_layer/tests/test_openCL_execution.cpp.i
.PHONY : opencl_layer/tests/test_openCL_execution.cpp.i

opencl_layer/tests/test_openCL_execution.s: opencl_layer/tests/test_openCL_execution.cpp.s

.PHONY : opencl_layer/tests/test_openCL_execution.s

# target to generate assembly for a file
opencl_layer/tests/test_openCL_execution.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/opencl_layer/tests/test_openCL_execution.cpp.s
.PHONY : opencl_layer/tests/test_openCL_execution.cpp.s

runtime_layer/classes/primitive_graph.o: runtime_layer/classes/primitive_graph.cpp.o

.PHONY : runtime_layer/classes/primitive_graph.o

# target to build an object file
runtime_layer/classes/primitive_graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/classes/primitive_graph.cpp.o
.PHONY : runtime_layer/classes/primitive_graph.cpp.o

runtime_layer/classes/primitive_graph.i: runtime_layer/classes/primitive_graph.cpp.i

.PHONY : runtime_layer/classes/primitive_graph.i

# target to preprocess a source file
runtime_layer/classes/primitive_graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/classes/primitive_graph.cpp.i
.PHONY : runtime_layer/classes/primitive_graph.cpp.i

runtime_layer/classes/primitive_graph.s: runtime_layer/classes/primitive_graph.cpp.s

.PHONY : runtime_layer/classes/primitive_graph.s

# target to generate assembly for a file
runtime_layer/classes/primitive_graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/classes/primitive_graph.cpp.s
.PHONY : runtime_layer/classes/primitive_graph.cpp.s

runtime_layer/classes/primitive_node.o: runtime_layer/classes/primitive_node.cpp.o

.PHONY : runtime_layer/classes/primitive_node.o

# target to build an object file
runtime_layer/classes/primitive_node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/classes/primitive_node.cpp.o
.PHONY : runtime_layer/classes/primitive_node.cpp.o

runtime_layer/classes/primitive_node.i: runtime_layer/classes/primitive_node.cpp.i

.PHONY : runtime_layer/classes/primitive_node.i

# target to preprocess a source file
runtime_layer/classes/primitive_node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/classes/primitive_node.cpp.i
.PHONY : runtime_layer/classes/primitive_node.cpp.i

runtime_layer/classes/primitive_node.s: runtime_layer/classes/primitive_node.cpp.s

.PHONY : runtime_layer/classes/primitive_node.s

# target to generate assembly for a file
runtime_layer/classes/primitive_node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/classes/primitive_node.cpp.s
.PHONY : runtime_layer/classes/primitive_node.cpp.s

runtime_layer/morsel_driven/exchange.o: runtime_layer/morsel_driven/exchange.cpp.o

.PHONY : runtime_layer/morsel_driven/exchange.o

# target to build an object file
runtime_layer/morsel_driven/exchange.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/morsel_driven/exchange.cpp.o
.PHONY : runtime_layer/morsel_driven/exchange.cpp.o

runtime_layer/morsel_driven/exchange.i: runtime_layer/morsel_driven/exchange.cpp.i

.PHONY : runtime_layer/morsel_driven/exchange.i

# target to preprocess a source file
runtime_layer/morsel_driven/exchange.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/morsel_driven/exchange.cpp.i
.PHONY : runtime_layer/morsel_driven/exchange.cpp.i

runtime_layer/morsel_driven/exchange.s: runtime_layer/morsel_driven/exchange.cpp.s

.PHONY : runtime_layer/morsel_driven/exchange.s

# target to generate assembly for a file
runtime_layer/morsel_driven/exchange.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/morsel_driven/exchange.cpp.s
.PHONY : runtime_layer/morsel_driven/exchange.cpp.s

runtime_layer/runtime_globals.o: runtime_layer/runtime_globals.cpp.o

.PHONY : runtime_layer/runtime_globals.o

# target to build an object file
runtime_layer/runtime_globals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/runtime_globals.cpp.o
.PHONY : runtime_layer/runtime_globals.cpp.o

runtime_layer/runtime_globals.i: runtime_layer/runtime_globals.cpp.i

.PHONY : runtime_layer/runtime_globals.i

# target to preprocess a source file
runtime_layer/runtime_globals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/runtime_globals.cpp.i
.PHONY : runtime_layer/runtime_globals.cpp.i

runtime_layer/runtime_globals.s: runtime_layer/runtime_globals.cpp.s

.PHONY : runtime_layer/runtime_globals.s

# target to generate assembly for a file
runtime_layer/runtime_globals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/runtime_globals.cpp.s
.PHONY : runtime_layer/runtime_globals.cpp.s

runtime_layer/tests/test_exchange_graph.o: runtime_layer/tests/test_exchange_graph.cpp.o

.PHONY : runtime_layer/tests/test_exchange_graph.o

# target to build an object file
runtime_layer/tests/test_exchange_graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/tests/test_exchange_graph.cpp.o
.PHONY : runtime_layer/tests/test_exchange_graph.cpp.o

runtime_layer/tests/test_exchange_graph.i: runtime_layer/tests/test_exchange_graph.cpp.i

.PHONY : runtime_layer/tests/test_exchange_graph.i

# target to preprocess a source file
runtime_layer/tests/test_exchange_graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/tests/test_exchange_graph.cpp.i
.PHONY : runtime_layer/tests/test_exchange_graph.cpp.i

runtime_layer/tests/test_exchange_graph.s: runtime_layer/tests/test_exchange_graph.cpp.s

.PHONY : runtime_layer/tests/test_exchange_graph.s

# target to generate assembly for a file
runtime_layer/tests/test_exchange_graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/tests/test_exchange_graph.cpp.s
.PHONY : runtime_layer/tests/test_exchange_graph.cpp.s

runtime_layer/tests/test_graph.o: runtime_layer/tests/test_graph.cpp.o

.PHONY : runtime_layer/tests/test_graph.o

# target to build an object file
runtime_layer/tests/test_graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/tests/test_graph.cpp.o
.PHONY : runtime_layer/tests/test_graph.cpp.o

runtime_layer/tests/test_graph.i: runtime_layer/tests/test_graph.cpp.i

.PHONY : runtime_layer/tests/test_graph.i

# target to preprocess a source file
runtime_layer/tests/test_graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/tests/test_graph.cpp.i
.PHONY : runtime_layer/tests/test_graph.cpp.i

runtime_layer/tests/test_graph.s: runtime_layer/tests/test_graph.cpp.s

.PHONY : runtime_layer/tests/test_graph.s

# target to generate assembly for a file
runtime_layer/tests/test_graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/tests/test_graph.cpp.s
.PHONY : runtime_layer/tests/test_graph.cpp.s

runtime_layer/tests/tpch_queries/query1.o: runtime_layer/tests/tpch_queries/query1.cpp.o

.PHONY : runtime_layer/tests/tpch_queries/query1.o

# target to build an object file
runtime_layer/tests/tpch_queries/query1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/tests/tpch_queries/query1.cpp.o
.PHONY : runtime_layer/tests/tpch_queries/query1.cpp.o

runtime_layer/tests/tpch_queries/query1.i: runtime_layer/tests/tpch_queries/query1.cpp.i

.PHONY : runtime_layer/tests/tpch_queries/query1.i

# target to preprocess a source file
runtime_layer/tests/tpch_queries/query1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/tests/tpch_queries/query1.cpp.i
.PHONY : runtime_layer/tests/tpch_queries/query1.cpp.i

runtime_layer/tests/tpch_queries/query1.s: runtime_layer/tests/tpch_queries/query1.cpp.s

.PHONY : runtime_layer/tests/tpch_queries/query1.s

# target to generate assembly for a file
runtime_layer/tests/tpch_queries/query1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/tests/tpch_queries/query1.cpp.s
.PHONY : runtime_layer/tests/tpch_queries/query1.cpp.s

runtime_layer/tests/tpch_queries/query6.o: runtime_layer/tests/tpch_queries/query6.cpp.o

.PHONY : runtime_layer/tests/tpch_queries/query6.o

# target to build an object file
runtime_layer/tests/tpch_queries/query6.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/tests/tpch_queries/query6.cpp.o
.PHONY : runtime_layer/tests/tpch_queries/query6.cpp.o

runtime_layer/tests/tpch_queries/query6.i: runtime_layer/tests/tpch_queries/query6.cpp.i

.PHONY : runtime_layer/tests/tpch_queries/query6.i

# target to preprocess a source file
runtime_layer/tests/tpch_queries/query6.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/tests/tpch_queries/query6.cpp.i
.PHONY : runtime_layer/tests/tpch_queries/query6.cpp.i

runtime_layer/tests/tpch_queries/query6.s: runtime_layer/tests/tpch_queries/query6.cpp.s

.PHONY : runtime_layer/tests/tpch_queries/query6.s

# target to generate assembly for a file
runtime_layer/tests/tpch_queries/query6.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/tests/tpch_queries/query6.cpp.s
.PHONY : runtime_layer/tests/tpch_queries/query6.cpp.s

runtime_layer/tests/tpch_queries/queryHashJoin.o: runtime_layer/tests/tpch_queries/queryHashJoin.cpp.o

.PHONY : runtime_layer/tests/tpch_queries/queryHashJoin.o

# target to build an object file
runtime_layer/tests/tpch_queries/queryHashJoin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/tests/tpch_queries/queryHashJoin.cpp.o
.PHONY : runtime_layer/tests/tpch_queries/queryHashJoin.cpp.o

runtime_layer/tests/tpch_queries/queryHashJoin.i: runtime_layer/tests/tpch_queries/queryHashJoin.cpp.i

.PHONY : runtime_layer/tests/tpch_queries/queryHashJoin.i

# target to preprocess a source file
runtime_layer/tests/tpch_queries/queryHashJoin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/tests/tpch_queries/queryHashJoin.cpp.i
.PHONY : runtime_layer/tests/tpch_queries/queryHashJoin.cpp.i

runtime_layer/tests/tpch_queries/queryHashJoin.s: runtime_layer/tests/tpch_queries/queryHashJoin.cpp.s

.PHONY : runtime_layer/tests/tpch_queries/queryHashJoin.s

# target to generate assembly for a file
runtime_layer/tests/tpch_queries/queryHashJoin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/runtime_layer/tests/tpch_queries/queryHashJoin.cpp.s
.PHONY : runtime_layer/tests/tpch_queries/queryHashJoin.cpp.s

src/hashArray.o: src/hashArray.cpp.o

.PHONY : src/hashArray.o

# target to build an object file
src/hashArray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/src/hashArray.cpp.o
.PHONY : src/hashArray.cpp.o

src/hashArray.i: src/hashArray.cpp.i

.PHONY : src/hashArray.i

# target to preprocess a source file
src/hashArray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/src/hashArray.cpp.i
.PHONY : src/hashArray.cpp.i

src/hashArray.s: src/hashArray.cpp.s

.PHONY : src/hashArray.s

# target to generate assembly for a file
src/hashArray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/src/hashArray.cpp.s
.PHONY : src/hashArray.cpp.s

src/hashing.o: src/hashing.cpp.o

.PHONY : src/hashing.o

# target to build an object file
src/hashing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/src/hashing.cpp.o
.PHONY : src/hashing.cpp.o

src/hashing.i: src/hashing.cpp.i

.PHONY : src/hashing.i

# target to preprocess a source file
src/hashing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/src/hashing.cpp.i
.PHONY : src/hashing.cpp.i

src/hashing.s: src/hashing.cpp.s

.PHONY : src/hashing.s

# target to generate assembly for a file
src/hashing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/src/hashing.cpp.s
.PHONY : src/hashing.cpp.s

task_layer/classes/data_pack.o: task_layer/classes/data_pack.cpp.o

.PHONY : task_layer/classes/data_pack.o

# target to build an object file
task_layer/classes/data_pack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/task_layer/classes/data_pack.cpp.o
.PHONY : task_layer/classes/data_pack.cpp.o

task_layer/classes/data_pack.i: task_layer/classes/data_pack.cpp.i

.PHONY : task_layer/classes/data_pack.i

# target to preprocess a source file
task_layer/classes/data_pack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/task_layer/classes/data_pack.cpp.i
.PHONY : task_layer/classes/data_pack.cpp.i

task_layer/classes/data_pack.s: task_layer/classes/data_pack.cpp.s

.PHONY : task_layer/classes/data_pack.s

# target to generate assembly for a file
task_layer/classes/data_pack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/task_layer/classes/data_pack.cpp.s
.PHONY : task_layer/classes/data_pack.cpp.s

task_layer/classes/kernel_pack.o: task_layer/classes/kernel_pack.cpp.o

.PHONY : task_layer/classes/kernel_pack.o

# target to build an object file
task_layer/classes/kernel_pack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/task_layer/classes/kernel_pack.cpp.o
.PHONY : task_layer/classes/kernel_pack.cpp.o

task_layer/classes/kernel_pack.i: task_layer/classes/kernel_pack.cpp.i

.PHONY : task_layer/classes/kernel_pack.i

# target to preprocess a source file
task_layer/classes/kernel_pack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/task_layer/classes/kernel_pack.cpp.i
.PHONY : task_layer/classes/kernel_pack.cpp.i

task_layer/classes/kernel_pack.s: task_layer/classes/kernel_pack.cpp.s

.PHONY : task_layer/classes/kernel_pack.s

# target to generate assembly for a file
task_layer/classes/kernel_pack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/task_layer/classes/kernel_pack.cpp.s
.PHONY : task_layer/classes/kernel_pack.cpp.s

task_layer/classes/task.o: task_layer/classes/task.cpp.o

.PHONY : task_layer/classes/task.o

# target to build an object file
task_layer/classes/task.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/task_layer/classes/task.cpp.o
.PHONY : task_layer/classes/task.cpp.o

task_layer/classes/task.i: task_layer/classes/task.cpp.i

.PHONY : task_layer/classes/task.i

# target to preprocess a source file
task_layer/classes/task.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/task_layer/classes/task.cpp.i
.PHONY : task_layer/classes/task.cpp.i

task_layer/classes/task.s: task_layer/classes/task.cpp.s

.PHONY : task_layer/classes/task.s

# target to generate assembly for a file
task_layer/classes/task.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/task_layer/classes/task.cpp.s
.PHONY : task_layer/classes/task.cpp.s

task_layer/task_globals.o: task_layer/task_globals.cpp.o

.PHONY : task_layer/task_globals.o

# target to build an object file
task_layer/task_globals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/task_layer/task_globals.cpp.o
.PHONY : task_layer/task_globals.cpp.o

task_layer/task_globals.i: task_layer/task_globals.cpp.i

.PHONY : task_layer/task_globals.i

# target to preprocess a source file
task_layer/task_globals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/task_layer/task_globals.cpp.i
.PHONY : task_layer/task_globals.cpp.i

task_layer/task_globals.s: task_layer/task_globals.cpp.s

.PHONY : task_layer/task_globals.s

# target to generate assembly for a file
task_layer/task_globals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/task_layer/task_globals.cpp.s
.PHONY : task_layer/task_globals.cpp.s

task_layer/tests/test_task_execution.o: task_layer/tests/test_task_execution.cpp.o

.PHONY : task_layer/tests/test_task_execution.o

# target to build an object file
task_layer/tests/test_task_execution.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/task_layer/tests/test_task_execution.cpp.o
.PHONY : task_layer/tests/test_task_execution.cpp.o

task_layer/tests/test_task_execution.i: task_layer/tests/test_task_execution.cpp.i

.PHONY : task_layer/tests/test_task_execution.i

# target to preprocess a source file
task_layer/tests/test_task_execution.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/task_layer/tests/test_task_execution.cpp.i
.PHONY : task_layer/tests/test_task_execution.cpp.i

task_layer/tests/test_task_execution.s: task_layer/tests/test_task_execution.cpp.s

.PHONY : task_layer/tests/test_task_execution.s

# target to generate assembly for a file
task_layer/tests/test_task_execution.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hero.dir/build.make CMakeFiles/Hero.dir/task_layer/tests/test_task_execution.cpp.s
.PHONY : task_layer/tests/test_task_execution.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Hero"
	@echo "... TPCH/common/algebra/Operators.o"
	@echo "... TPCH/common/algebra/Operators.i"
	@echo "... TPCH/common/algebra/Operators.s"
	@echo "... TPCH/common/algebra/Pipeline.o"
	@echo "... TPCH/common/algebra/Pipeline.i"
	@echo "... TPCH/common/algebra/Pipeline.s"
	@echo "... TPCH/common/algebra/Types.o"
	@echo "... TPCH/common/algebra/Types.i"
	@echo "... TPCH/common/algebra/Types.s"
	@echo "... TPCH/common/runtime/Concurrency.o"
	@echo "... TPCH/common/runtime/Concurrency.i"
	@echo "... TPCH/common/runtime/Concurrency.s"
	@echo "... TPCH/common/runtime/Database.o"
	@echo "... TPCH/common/runtime/Database.i"
	@echo "... TPCH/common/runtime/Database.s"
	@echo "... TPCH/common/runtime/Hashmap.o"
	@echo "... TPCH/common/runtime/Hashmap.i"
	@echo "... TPCH/common/runtime/Hashmap.s"
	@echo "... TPCH/common/runtime/Import.o"
	@echo "... TPCH/common/runtime/Import.i"
	@echo "... TPCH/common/runtime/Import.s"
	@echo "... TPCH/common/runtime/MemoryPool.o"
	@echo "... TPCH/common/runtime/MemoryPool.i"
	@echo "... TPCH/common/runtime/MemoryPool.s"
	@echo "... TPCH/common/runtime/Profile.o"
	@echo "... TPCH/common/runtime/Profile.i"
	@echo "... TPCH/common/runtime/Profile.s"
	@echo "... TPCH/common/runtime/String.o"
	@echo "... TPCH/common/runtime/String.i"
	@echo "... TPCH/common/runtime/String.s"
	@echo "... TPCH/common/runtime/Types.o"
	@echo "... TPCH/common/runtime/Types.i"
	@echo "... TPCH/common/runtime/Types.s"
	@echo "... TPCH/tpch_globals.o"
	@echo "... TPCH/tpch_globals.i"
	@echo "... TPCH/tpch_globals.s"
	@echo "... cpp_layer/cpp_globals.o"
	@echo "... cpp_layer/cpp_globals.i"
	@echo "... cpp_layer/cpp_globals.s"
	@echo "... cpp_layer/operations/primitives.o"
	@echo "... cpp_layer/operations/primitives.i"
	@echo "... cpp_layer/operations/primitives.s"
	@echo "... cpp_layer/tests/test_cpp_execution.o"
	@echo "... cpp_layer/tests/test_cpp_execution.i"
	@echo "... cpp_layer/tests/test_cpp_execution.s"
	@echo "... globals.o"
	@echo "... globals.i"
	@echo "... globals.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... opencl_layer/classes/devices.o"
	@echo "... opencl_layer/classes/devices.i"
	@echo "... opencl_layer/classes/devices.s"
	@echo "... opencl_layer/classes/platforms.o"
	@echo "... opencl_layer/classes/platforms.i"
	@echo "... opencl_layer/classes/platforms.s"
	@echo "... opencl_layer/openCL_globals.o"
	@echo "... opencl_layer/openCL_globals.i"
	@echo "... opencl_layer/openCL_globals.s"
	@echo "... opencl_layer/tests/test_openCL_execution.o"
	@echo "... opencl_layer/tests/test_openCL_execution.i"
	@echo "... opencl_layer/tests/test_openCL_execution.s"
	@echo "... runtime_layer/classes/primitive_graph.o"
	@echo "... runtime_layer/classes/primitive_graph.i"
	@echo "... runtime_layer/classes/primitive_graph.s"
	@echo "... runtime_layer/classes/primitive_node.o"
	@echo "... runtime_layer/classes/primitive_node.i"
	@echo "... runtime_layer/classes/primitive_node.s"
	@echo "... runtime_layer/morsel_driven/exchange.o"
	@echo "... runtime_layer/morsel_driven/exchange.i"
	@echo "... runtime_layer/morsel_driven/exchange.s"
	@echo "... runtime_layer/runtime_globals.o"
	@echo "... runtime_layer/runtime_globals.i"
	@echo "... runtime_layer/runtime_globals.s"
	@echo "... runtime_layer/tests/test_exchange_graph.o"
	@echo "... runtime_layer/tests/test_exchange_graph.i"
	@echo "... runtime_layer/tests/test_exchange_graph.s"
	@echo "... runtime_layer/tests/test_graph.o"
	@echo "... runtime_layer/tests/test_graph.i"
	@echo "... runtime_layer/tests/test_graph.s"
	@echo "... runtime_layer/tests/tpch_queries/query1.o"
	@echo "... runtime_layer/tests/tpch_queries/query1.i"
	@echo "... runtime_layer/tests/tpch_queries/query1.s"
	@echo "... runtime_layer/tests/tpch_queries/query6.o"
	@echo "... runtime_layer/tests/tpch_queries/query6.i"
	@echo "... runtime_layer/tests/tpch_queries/query6.s"
	@echo "... runtime_layer/tests/tpch_queries/queryHashJoin.o"
	@echo "... runtime_layer/tests/tpch_queries/queryHashJoin.i"
	@echo "... runtime_layer/tests/tpch_queries/queryHashJoin.s"
	@echo "... src/hashArray.o"
	@echo "... src/hashArray.i"
	@echo "... src/hashArray.s"
	@echo "... src/hashing.o"
	@echo "... src/hashing.i"
	@echo "... src/hashing.s"
	@echo "... task_layer/classes/data_pack.o"
	@echo "... task_layer/classes/data_pack.i"
	@echo "... task_layer/classes/data_pack.s"
	@echo "... task_layer/classes/kernel_pack.o"
	@echo "... task_layer/classes/kernel_pack.i"
	@echo "... task_layer/classes/kernel_pack.s"
	@echo "... task_layer/classes/task.o"
	@echo "... task_layer/classes/task.i"
	@echo "... task_layer/classes/task.s"
	@echo "... task_layer/task_globals.o"
	@echo "... task_layer/task_globals.i"
	@echo "... task_layer/task_globals.s"
	@echo "... task_layer/tests/test_task_execution.o"
	@echo "... task_layer/tests/test_task_execution.i"
	@echo "... task_layer/tests/test_task_execution.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

